# Generated by Django 4.2.5 on 2023-10-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='altaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de Cliente')),
                ('email', models.CharField(max_length=255, verbose_name='Mail del Cliente')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular del Cliente')),
            ],
        ),
    ]
